# Generated by Django 2.2.7 on 2019-12-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(default='123 Place Drive', max_length=35),
            preserve_default=False,
        ),
    ]
