# Generated by Django 2.2.7 on 2019-12-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
