# Generated by Django 2.2.7 on 2019-12-05 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191205_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='max_amount',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reorder_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reorder_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='DOT',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 0, 40, 50, 776472)),
        ),
    ]
