# Generated by Django 2.2.7 on 2019-12-05 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191205_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_card',
            name='card_number',
            field=models.CharField(default='1234 2345 3456 4567', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='DOT',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 3, 27, 20, 407232)),
        ),
    ]
