# Generated by Django 2.2.7 on 2019-12-05 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191205_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='DOT',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 3, 29, 24, 134882)),
        ),
        migrations.AlterField(
            model_name='saved_card',
            name='card_number',
            field=models.CharField(max_length=30),
        ),
    ]
